### ISSUE TITLE
Question in force computation

### ISSUE THREAD

**Issue by ztz1995** [petervanya/DPDsim#1]
Hi, I'm reading your paper about GMDPD and deeply inspired.
However, I found a mismatch about your code and paper.
In the paper, the force is calculate as follow:
$ F_ij = 15 / (\pi r_d^4)B(\rou_i + \rou_j)(1 - r/r_d) $,
then, B=2.
However, in your code, the force is calcualted by:
`            fpair = A * wr(nr) \
                + ip_B * (rhoi + rhoj) * wr(nr / rd) \
                - gamma * wr(nr)**2 * dot_numba(rij, vij) / nr \
                + sqrt(2.0*gamma*kT) * wr(nr) * np.random.randn() / sqrt(dt)
`
where I couldn't find the 15 / (\pi r_d^4).
Is this a bug, or am I understanding it wrong?
Looking forward to your reply.
Thank you!

**Comment by petervanya** [comment]
Hello, thanks for the message, you could be right there is a missing prefactor. 
I had a quick look but please give me a few more days so that I can check it thoroughly.

**Comment by petervanya** [comment]
Hello, thanks for patience and sorry for my belated response. I rechecked the code and calculations and I think there should be no problem:

- Considering [GMDPD](https://github.com/petervanya/DPDsim/blob/master/dpdsim/gmdpd.py), in `force_numba` there is a normalisation constant `nrm` on line 524.

- Considering more constrained [EMDPD](https://github.com/petervanya/DPDsim/blob/master/dpdsim/emdpd.py), which is effectively a redefined MDPD, there is `nrm` also defined on line 464  for `force_numba`. There is the factor `15/(2pi rd^3)` in `nrm` and further `2/rd` on line 467, which adds up to the `15/(pi rd^4)` that you mention.

- The same applies to the [Fortran scripts](https://github.com/petervanya/DPDsim/tree/master/dpdsim/Fdpd).

Hope this makes sense, please let me know if I can help further in case you would like to apply this force field to your system.

**Comment by ztz1995** [comment]
> Hello, thanks for patience and sorry for my belated response. I rechecked the code and calculations and I think there should be no problem:
> 
> * Considering [GMDPD](https://github.com/petervanya/DPDsim/blob/master/dpdsim/gmdpd.py), in `force_numba` there is a normalisation constant `nrm` on line 524.
> * Considering more constrained [EMDPD](https://github.com/petervanya/DPDsim/blob/master/dpdsim/emdpd.py), which is effectively a redefined MDPD, there is `nrm` also defined on line 464  for `force_numba`. There is the factor `15/(2pi rd^3)` in `nrm` and further `2/rd` on line 467, which adds up to the `15/(pi rd^4)` that you mention.
> * The same applies to the [Fortran scripts](https://github.com/petervanya/DPDsim/tree/master/dpdsim/Fdpd).
> 
> Hope this makes sense, please let me know if I can help further in case you would like to apply this force field to your system.

Thanks for your detailed answer. The above code in my issue was cited from mdpd.py,  line 461. Maybe there is no need for nomarlisation in mdpd?
We do want to try to apply gmdpd in our system. Can you give your email that I can talk about my problem in detail?

**Comment by petervanya** [comment]
The code in `mdpd.py` is the implementation of many-body DPD from [the Warren paper](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.68.066702) and so it does not adhere to the normalisation rules presented in [our paper](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.102.013312).

Please contact me on the email in our paper, peter.vanya~gmail.
